### ISSUE TITLE
Scope out needs and approaches

### ISSUE THREAD

**Issue by patrickmj** [omeka/plugin-VraCore#1]
So far, I see three approaches, in increasing complexity.
## Simple Element Set

Would just include the 19 VRA Elements, plus the 3 VRA Types as Omeka Item Types. This, essentially, would be the equivalent of only using the <display> XML element inside VRA's <{whateverVRAElement}Set> pattern. This is pretty much what the old version did. 

Pros: Dead simple, done very quickly

Cons: Fairly useless. The same effect could be achieved via the admin interface by creating the appropriate Item Types and Elements. Also, if there's a strong thread of using this for teaching, the interesting parts of the VRA standard will be completely ignored.
## Element Set Plus

Would start with the Simple Element Set, then add additional db tables (not part of the element set system) to handle the additional, interesting data represented in VRA as XML subelements and attributes. 

Pros: Gets at what VRA emphasizes; provides a path for teaching the metadata standard in-depth

Cons: Much more complicated, requiring new database tables and complex relations between them; user interface could also be complicated; not immediately obvious if/how it could work, so there would be some exploration and discovery time
## Element Set Plus with XML

Same as above, but includes exporting as a VRA Core compliant XML document.

Pros: Same as above; moves toward the work done being useful as real VRA data in the world

Cons: Same as above, but might require more precise database design; additional time to add the XML export

**Comment by patrickmj** [comment]
@sheilabrennan here's some notes on what looks possible right now for VRA. Thoughts?

Preliminary work toward option 2 (Element Set Plus) looks like these features:
- A regular element set tab for VRA Elements. The usual inputs would be treated as the &lt;display> optional element. This would allow for the easy display on the web, but introduces the possibility for people to enter multiple `display` elements, which is not allowed in the VRA spec.
- Under the usual input, add inputs for VRA global attributes, element-specific attributes, andsubelements (with their specific attributes) where appropriate. These would not be stored as Omeka ElementTexts, but as their own data in separate tables.

Roughly it'd start looking like this

![vra](https://cloud.githubusercontent.com/assets/153262/10801821/b99eba26-7d8f-11e5-8c9e-dc464cabfa71.png)

For the `dataDate` attribute, I'd probably just automate that for everything. The `pref` attribute for preferred values would be recorded, but not actually implemented on the actual display since that would get into conflicts between Element display and the additional data that's not stored as ElementTexts.

Megan pointed me toward some GMU librarians who are interested in VRA and Omeka, so I hope to get insights and ideas from them, but this seems like a pretty reasonable balance of fidelity to VRA's spec and what Omeka can do.

Not really sure how to make it go with CSV import, but I _think_ at least some of the attribute and subelement stuff would be workable, depending on typical CSV structure

Still hard to know a precise timeline, but at this stage I'd put it on the order of 4 or 5 sprints.

**Comment by sheilabrennan** [comment]
@patrickmj thanks for spec'ing this out. It's helpful to see the options. 

Can option 2 be built, so that we have something concrete to test, and then add the XML compliant document later?  

Kimon is involved with this grant will definitely test and offer feedback on this plugin. I had already emailed him with some questions about this, but your explanations above offer some more concrete things to consider. What if I email him and cc you, and get some conversation going about that now?

**Comment by patrickmj** [comment]
@sheilabrennan sounds good to me. I'm aiming at option 2 as I've been building/exploring.

**Comment by patrickmj** [comment]
Convos with Kimon and Fenwick library folks continues at least through Nov 10. Worth a new pile of issues based on those, if #7 #6 #5 #4 #3 #2 are no longer in scope (I think they should be)
