### ISSUE TITLE
Deactivating plugin does not remove elements

### ISSUE THREAD

**Issue by mebrett** [omeka/plugin-VraCore#42]
If I deactivate the VRA Core plugin (but do not uninstall), the VRA Core tab on Edit Item remains and the the VRA elements load like normal Omeka elements, with "Add Input" etc.

There was at least one item in the install with VRA core data when I deactivated it, for what it's worth.

**Comment by mebrett** [comment]
Elements remain because the element set remains - can/do we want to add an alert when deactivating, or is this an "emphasize in documentation?" issue?

**Comment by patrickmj** [comment]
Options are slim to none for deactivating. Worth noting that the same issue should be there for uninstalling, and there are better options there.

For both, though, emphasis in documentation seems like a good thing
