### ISSUE TITLE
Changes saved but not displayed

### ISSUE THREAD

**Issue by mebrett** [omeka/plugin-VraCore#49]
If I go in and edit an item's VRA core information, the changes are apparently saved (I can see them when I edit again) but the new information does not display on the admin or public item/show. 

This is with no configuration on the plugin, and with various combinations of the checkboxes on and off.

**Comment by patrickmj** [comment]
Looks like this happens when there's only the vra display value (aka the Omeka element text) , and no other vra data. Guessing it's a bug in how I'm avoiding the option for 'hide empty elements'
