### ISSUE TITLE
Testing all the inputs

### ISSUE THREAD

**Issue by patrickmj** [omeka/plugin-VraCore#84]
VRA Core is ready for a new look. The big new thing is to look at all the possibilities for VRA Core data, all the way down to the deepest nesting options. About half the elements have subelements to check for (they should all have the little collapse/uncollapse button).

Agent->dates has the bonus extra level for earliest and latest date.

For all of those, there's also adding some attributes.

Also, check that it all works when you add new elements via the green buttons.

Those should be tested for both adding and editing items.

The thing to look for is just whether the right data is saved to the right element, subelement, attribute, etc.

As many of those variations (there's a lot!) you can check on, the better.

**Comment by patrickmj** [comment]
I put up a new release candidate today, v1.1-rc2. I don't think it affects much on the admin side -- mostly just producing XML output, but still might be worth updating to that tag.

**Comment by mebrett** [comment]
Add new elements works fine. Everything I can think to put in displays on both admin and public sides (since I have that turned on) and multiple elements with various attributes all display properly.
And the 'circa' checkbox for earliest and latest dates works - displays as "circa true"

**Comment by patrickmj** [comment]
Many thanks -- I know that must've a long, tedious grind to churn through. Next work will have to come from outside reviewers
