### ISSUE TITLE
Newly created elements are missing attributes

### ISSUE THREAD

**Issue by kimisgold** [omeka/plugin-VraCore#95]
<img width="395" alt="screen shot 2016-07-14 at 5 26 33 pm" src="https://cloud.githubusercontent.com/assets/606764/16856509/6a2010aa-49e8-11e6-9856-b132cdb61f2c.png">

In this example, I clicked "Add VRA Inscription element" button. It created the top "Inscription Subelements" panel. The existing panel at bottom contains the "Attributes" option set while the new panel up top does not.

**Comment by patrickmj** [comment]
I'll have to double-check the schema, but the bug might actually be the other way around, that for deeply-nested element like Inscription and Agent, there should not be attributes at that level. 

If there are attributes at that level, they should probably be moved outside of subelements
