### ISSUE TITLE
Location subelement names repeat in public view

### ISSUE THREAD

**Issue by kimisgold** [omeka/plugin-VraCore#97]
This is the Omeka/VraCore-generated XML data for my 'Location' element:

```
<locationSet>
    <display>Chartres, Centre, France</display>
    <location dataDate="2016-07-14 17:41:35">
        <name dataDate="2016-07-14 17:41:35" type="geographic" extent="region">Centre</name>
    </location>
    <location dataDate="2016-07-14 17:41:35" vocab="TGN">
        <name dataDate="2016-07-14 17:41:35" type="geographic" extent="inhabited place">Chartres</name>
    </location>
    <location dataDate="2016-07-14 17:42:29">
        <name dataDate="2016-07-14 17:42:29" type="geographic" extent="nation" refid="7002877" vocab="TGN">France</name>
    </location>
</locationSet>
```

This is how it is rendered in the public view:

<img width="308" alt="screen shot 2016-07-15 at 4 10 14 pm" src="https://cloud.githubusercontent.com/assets/606764/16887270/f0cc9c0e-4aa6-11e6-844b-aca363435351.png">

**Comment by patrickmj** [comment]
This looks like the screenshot is from the master branch? It looks fixed on your show-views branch to me. Is that correct?

**Comment by kimisgold** [comment]
Yes, I submitted that issue before I made that branch. I removed it in the branch when I was trying to suss out the hierarchy. If it's actually necessary for something, I can put it back in so it can be merged, but the rendering seemed better without that extra label.

**Comment by patrickmj** [comment]
I remember that somewhere when I was going through things it made sense to add it. I think it was the circumstance where the appropriate label got bumped to the bottom of the list of data (subelements and attributes). I went back and forth about whether it was helpful or not to duplicate appropriate labels above the attributes, and when it can get bumped farther down when there are more subelements. I'll go with whatever you think is best

![location](https://cloud.githubusercontent.com/assets/153262/16931267/13c6b0fa-4d0e-11e6-9a21-49c0dc74a431.png)
